
const AUTHORITIES_QUERY = "/authorities-query";
const AUTHORITIES_QUERY__AUTHORITY = `${AUTHORITIES_QUERY}/authority/`;
const DOMAINS_POPULARITY_QUERY = "/domains-query";

export {
    AUTHORITIES_QUERY,
    AUTHORITIES_QUERY__AUTHORITY,
    DOMAINS_POPULARITY_QUERY,
}